tests clarification
fullstack-development/haskell-internship pull request #16
Opened 2022-12-04 10:28 UTC by olegromashin

2023-01-05 08:27 UTC, stanislav-az requested changes

2023-01-05 08:27 UTC, stanislav-az commented on bot-task.md
> +6. Проект должен быть покрыт unit-тестами, которые бы покрывали бизнес-логику приложения.
"покрыт, которые бы покрывали" не звучит по-моему, можно написать "которые бы проверяли соответствие корректной бизнес-логике приложения"

2024-09-27 15:11 UTC, olgaklimenko approved these changes

2024-09-30 06:25 UTC, roman-bodavskiy approved these changes

2024-09-30 08:05 UTC, kelizarov approved these changes

2024-10-01 12:08 UTC, stanislav-az approved these changes

2024-10-02 03:35 UTC, merged